import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/profile.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          RacketBrackets
        </h1>

        <div className={styles.navbar}>
            <ul>
                <li><a href="#profile">My Profile</a></li>
                <li><a href="#home">My Clubs</a></li>
                <li><a href="#home">My Matches</a></li>
                <li><a href="#home">My Messages</a></li>
                <li><a href="#home">Search</a></li>
            </ul>
            
        </div>
      </main>

    </div>
  )
}
